# Generated by Django 5.2.4 on 2025-11-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customerprofile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="selleraccount",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="sellers/"
            ),
        ),
    ]
