# Generated by Django 5.2.4 on 2025-11-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_selleraccount_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="selleraccount",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
