"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta


AUTH_USER_MODEL = "accounts.User"  # Use custom user model

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"  # For product images
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "insecure-dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"
# ALLOWED_HOSTS: localhost + Emulator + Real Device
ALLOWED_HOSTS = ["*"]

# CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev
    "http://10.0.2.2:8000",  # Android Emulator
]
CORS_ALLOW_CREDENTIALS = True  # for JWT cookies

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "accounts",  # Custom user app
    "addresses",  # Address management app
    "products",
    "carts",
    "wishlists",
    "support.apps.SupportConfig",
    "orders",
    "payments",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Allow cookies to be set for frontend
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",  # React dev server
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "dropz_db"),
        "USER": os.environ.get("DB_USER", "dropz_user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "dropz_password"),
        "HOST": os.environ.get("DB_HOST", "db"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation." "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration

CORS_ALLOWED_ORIGINS = ["http://localhost:3000"]

CORS_ALLOW_CREDENTIALS = True  # for JWT

# === Jazzmin settings ===
JAZZMIN_SETTINGS = {
    # Basic Info
    "site_title": "Dropz Admin",
    "site_header": "Dropz Support Panel",
    "site_brand": "Dropz",
    "welcome_sign": "Welcome to Dropz Admin",
    # UI Configuration
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    # Original-Style Sidebar
    "order_with_respect_to": ["auth", "support", "accounts", "products"],
    # Icons
    "icons": {
        "support.SupportTicket": "fas fa-ticket-alt",
        "support.TicketMessage": "fas fa-comments",
        "auth.User": "fas fa-user",
        "accounts.User": "fas fa-user",
    },
    # Disable UI modifications
    "show_ui_builder": False,
    "custom_links": {},
}

JAZZMIN_UI_TWEAKS = {
    # Dark Theme Configuration
    "theme": "dark",  # Changed from "light" to "dark"
    "navbar": "navbar-dark",  # Dark navbar
    "navbar_fixed": True,
    "sidebar": "sidebar-dark-primary",  # Dark sidebar
    # Original Layout Behavior
    "sidebar_nav_small_text": False,
    "sidebar_nav_flat_style": False,
    "sidebar_nav_legacy_style": True,  # Maintains original indentation
    "sidebar_nav_compact_style": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    # Color Scheme
    "brand_colour": "navbar-dark",  # Dark brand color
    "accent": "accent-lighten",  # Light accent for contrast
    # Disable Modern Features
    "actions_sticky_top": False,
}

PAYMOB = {
    "API_KEY": os.getenv("PAYMOB_API_KEY"),
    "INTEGRATION_ID_CARD": int(os.getenv("PAYMOB_INTEGRATION_ID_CARD", "0")),
    "IFRAME_ID": os.getenv("PAYMOB_IFRAME_ID"),
    "HMAC_SECRET": os.getenv("PAYMOB_HMAC_SECRET"),
    "BASE_URL": os.getenv("PAYMOB_BASE_URL", "https://accept.paymob.com/api"),
}
