# Generated by Django 5.2.4 on 2025-08-26 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("paymob", "Paymob"),
                            ("cash", "Cash on Delivery"),
                            ("card", "Credit Card"),
                        ],
                        default="paymob",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paymob_transaction_id",
                    models.TextField(blank=True, null=True),
                ),
                ("paymob_order_id", models.TextField(blank=True, null=True)),
                (
                    "paymob_payment_key",
                    models.TextField(blank=True, null=True),
                ),
                ("response_payload", models.JSONField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
